/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: 'ap-south-1',
    aws_cognito_region: 'ap-south-1',
    aws_user_pools_id: 'ap-south-1_tE7fJbGgu',
    aws_user_pools_web_client_id: '16p6fn947dm8ckr19bkra1vau1',
    aws_cognito_username_attributes: ['EMAIL'],
    aws_cognito_password_protection_settings: {
        passwordPolicyMinLength: 8,
        passwordPolicyCharacters: [],
    },
    Storage: {
        S3: {
            bucket: 'mm-dev-media-bucket',
            region: 'ap-south-1',
        },
    },
}

export default awsmobile
